name: Java Spring Boot and React CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 17 for Java Spring Boot
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      # Build Java Spring Boot Backend
      - name: Build Backend
        run: |
          cd backend
          chmod +x mvnw             # Ensure mvnw is executable
          ./mvnw clean install
          cd ..

      # Install Node.js for React
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      # Build React Frontend
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build
          cd ..

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Push Docker Image for Backend
      - name: Build and Push Backend Docker Image
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/cicd-backend:latest
          cd ..

      # Build and Push Docker Image for Frontend
      - name: Build and Push Frontend Docker Image
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd-frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/cicd-frontend:latest
